name: PUSH - build and release
on:
  push:
    branches:
    - master
    tags:
    - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: make test
      run: make test

    - name: make build
      run: make build

    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/certctl
